name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify Java distribution (like OpenJDK, Temurin, etc.)

      - name: Run build with MaxRAM flag
        run: |
          export MAVEN_OPTS="-XX:MaxRAM=2g"  # Set MaxRAM flag
          mvn clean install  # Run Maven build
          
      # Check if the compilation was successful with 2GB RAM
      - name: Check if build was successful with 2GB RAM
        if: success()  
        run: echo "The build with 2GB RAM was successful."

      # Check error
      - name: Handle failure
        if: failure()  
        run: echo "Build with 2GB RAM failed."
