name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    # - name: Get JaCoCo Coverage
    #   id: coverage  
    #   run: |
    #     coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
    #     echo "COVERAGE=$coverage" >> $GITHUB_ENV

    # - name: Fail if coverage has not improved.
    #   run: |
    #     coverage=$COVERAGE
    #     threshold=24.46
    #     if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
    #       echo "Coverage is not improved."
    #       exit 1
    #     else
    #       echo "New coverage: $coverage%. Coverage is improved!"
    #     fi

          ### RAM TEST    
          
    # - name: Run build with MaxRAM flag
    #   run: |
    #     export MAVEN_OPTS="-XX:MaxRAM=2g"  # Set MaxRAM flag
    #     mvn clean install  # Run Maven build
        
    # # Check if the compilation was successful with 2GB RAM
    # - name: Check if build was successful with 2GB RAM
    #   if: success()  
    #   run: echo "The build with 2GB RAM was successful."

    # # Check error
    # - name: Handle failure
    #   if: failure()  
    #   run: echo "Build with 2GB RAM failed."

          ### Ratio of heap USE
          
    # - name: flag
    #   run: |
    #     export MAVEN_OPTS="-Xlog:gc*:file=gc.log"  
    #     mvn clean install  # Run Maven build

    # - name: Ejecutar script de Bash para obtener GC Info
    #   run: |
    #     chmod +x ./search_gc_info.sh
    #     ./search_gc_info.sh

          #### CACHE TEST
          
    # - name: Run build with Cahce flag
    #   run: |
    #     export MAVEN_OPTS="-XX:ReservedCodeCacheSize=1024M"  
    #     mvn clean install  # Run Maven build
            
    # # Check if the compilation was successful with 1024M Cache
    # - name: Check if build was successful with 1024M Cache
    #   if: success()  
    #   run: echo "The build with 1024M Cache was successful."

    # # Check error
    # - name: Handle failure
    #   if: failure()  
    #   run: echo "Build with 1024M Cache failed."

          ### 64 vs 32 bits
    
    # First run with 1024M cache size
    - name: Run build with 1024M Cache flag
      run: |
        export MAVEN_OPTS="-XX:+UnlockDiagnosticVMOptions -XX:MallocMaxTestWords=1024M"
        mvn clean install
          
    # Check if the first build was successful
    - name: Check if build was successful with 128M Words
      id: check_build_1
      if: success()  
      run: echo "The build with 128 Words was successful."

    # Handling failure on first build
    - name: Handle failure for 128 Words
      if: failure()  
      run: echo "Build with 128 Words failed."

    # Second run with 64M Words (half)
    - name: Run build with 64M Words flag
      run: |
        export MAVEN_OPTS="-XX:+UnlockDiagnosticVMOptions -XX:MallocMaxTestWords=512M"
        mvn clean install

    # Check if the second build was successful
    - name: Check if build was successful with 64M Words
      id: check_build_2
      if: success()  
      run: echo "The build with 64M Words was successful."

    # Handling failure on second build
    - name: Handle failure for 64M Words
      if: failure()  
      run: echo "Build with 64M Words failed."

    # Evaluate overall success
    - name: Evaluate overall success
      run: |
        if [[ "${{ steps.check_build_1.outcome }}" == "success" ]] && [[ "${{ steps.check_build_2.outcome }}" == "success" ]]; then
          echo "It is very likely that the software will run on both architectures."
        elif [[ "${{ steps.check_build_1.outcome }}" == "failure" ]] && [[ "${{ steps.check_build_2.outcome }}" == "failure" ]]; then
          echo "Both builds failed. Try to increase the number of words for 64-bit architecture"
        else
          echo "It is very likely that the software will only run on 64-bit architectures."
        fi
